config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  root 'static_pages#home'

  get '/login' => 'static_pages#login'

  get '/about' => 'static_pages#about'

  get '/contact' => 'static_pages#contact'

  get '/signup' => 'users#new'

  resources :users

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true, length: {maximum: 50}
  validates :email,uniqueness:true, presence: true, length: {maximum: 255}
  validates :username,uniqueness:true, presence: true, length: {maximum: 20}
  validates_format_of :username, :with => /\A[a-z0-9\-_]+\z/i
  validates_format_of :email, :with => /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :password , presence:true,length: {minimum: 6}
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  has_secure_password
  def before_save
    self.email.downcase!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def login
  end

  def about
  end

  def contact
  end

  def signup
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(users_params)
    if @user.save
      flash[:success] =  @user.name+" "+"أهلا بيك يا "
      redirect_to @user
    else
      render 'new'
    end
  end

  private
  def users_params
    params.require(:user).permit(:name, :email, :username, :password, :password_confirmation,:avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def make_title(page_name ='',base)
    if !page_name.empty?
      "#{page_name} | #{base}"
    else
      "#{base}"
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<%= provide :app_name,'تملي معاك' %>
<!DOCTYPE html>
<html>
<head>
  <title><%= make_title(yield(:title), yield(:app_name)) %></title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="header">
  <header>
    <h1>&nbsp;&nbsp;<a href="/"> <%= yield(:app_name) %> </a></h1>
    <ul>
      <li><%= link_to 'دخول مفاجئ', login_path %></li>
      <li><%= link_to 'إحنا مين بئا', about_path %></li>
    </ul>
  </header>
  <br>
  <br>
  </div>
<br>
<div id="context">
  <% flash.each do |message_type, message| %>
      <div class="alert-<%= message_type %>"><%= message %></div>
  <% end %>
  <%= yield %>
</div>

<div id="footer">
  <footer>
    &nbsp;&nbsp;
    معمول بحنية by <a href="http://github.com/JiMadness" target="_blank">JiMadness</a>
    <ul>
      <li><%= link_to 'إحنا مين',about_path %></li>
      <li><%= link_to 'ممكن نتعرف؟',contact_path %></li>
    </ul>
  </footer>
</div>
<%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/shared/_error_messages.erb
<% if @user.errors.any? %>
    <div id="error">
      <div class="alert alert-danger">
        The form contains <%= pluralize(@user.errors.count, "error") %>:
      </div>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/static_pages/about.html.erb
<%= provide :title, 'احنا مين' %>
<div class="static-background"></div>
<div id="about-us">
  <h1>إحنا مين؟</h1>
  <p>تملي معاك هو موقع تواصل اجتماعي عمله محمد جمال في ألفين و ستاشر ..
    أنا لسا مش عارف كل التفاصيل حاليا بس ان شاء الله ربنا هيكرم يعني </p>
</div>

app/views/static_pages/contact.erb
<%= provide :title, 'نحب نتعرف' %>
<div class="static-background"></div>
<div id="about-us">
  <h1>نحب نتعرف .. ورانا ايه</h1>
  <p>كلمني على 01002199674 .. و ياريت لو تشحنلي ب10 ولا حاجة</p>
</div>

app/views/static_pages/home.html.erb
<div class="static-background"></div>
<div id="welcome" class="center">
<h1>أهلا أهلا بالفرسان</h1>
<h5>متزغرطوش غير لما تنبسطو</h5>
<h1 id="join"><%= link_to '!إنضم إلينا ' , signup_path %></h1>
</div>

app/views/static_pages/login.html.erb
<%= provide :title, 'دخول مفاجئ' %>
<div class="static-background"></div>
<h1>StaticPages#login</h1>
<p>Find me in app/views/static_pages/login.html.erb</p>

app/views/users/new.html.erb
<%= provide :title, 'إنضم إلينا' %>
<div class="static-background"></div>
<h1>&nbsp;&nbsp; إنضم إلينا</h1>
<br>
<div id="signup-form">
  <%= form_for @user ,:html => { :'data-ajax' => false } do |f| %>
      <%= render 'shared/error_messages' %>
      <%= f.text_field :name %>
      <%= f.label :name, "إسمك" %>
      <br>
      <%= f.text_field :username %>
      <%= f.label :username, "اليوزرنيم .. الهاندل .. ولا بتسميه ايه لما تكتبه" %>
      <br>
      <%= f.email_field :email %>
      <%= f.label :email, "بريدك الإلكتروني الروش جدا" %>
      <br>
      <%= f.label :avatar,"صورتك السيكسي يا سيكسي"%>
      <br>
      <%= f.file_field :avatar %>
      <br>
      <%= f.password_field :password %>
      <%= f.label :password, "(كلمة السر:جزر (اوعى تكتبها جزر بجد" %>
      <br>
      <%= f.password_field :password_confirmation %>
      <%= f.label :password_confirmation, "الباسوورد تاني ونبي كدة" %>
      <br>
      <br>
      <br>
      <%= f.submit "على بركة الله", id: "submit" %>
  <% end %>
</div>

app/views/users/show.erb
<%= provide :title ,@user.name %>
<div id="profile-info">
  <%= image_tag @user.avatar.url(:medium)%>
  <h1 class="user-info"><%= @user.name %></h1>
  <h3 class="user-info"><%= @user.email %></h3>
</div>